/* Form definition file generated by fdesign on Sat May 17 16:02:54 2025 */

#include <stdlib.h>
#include "watch.h"


/***************************************
 ***************************************/

FD_watch_top *
create_form_watch_top( void )
{
    FL_OBJECT *obj;
    FD_watch_top *fdui = ( FD_watch_top * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->watch_top = fl_bgn_form( FL_NO_BOX, 434, 466 );

    obj = fl_add_box( FL_FLAT_BOX, 0, 0, 434, 466, "" );

    fdui->clock = obj = fl_add_button( FL_NORMAL_BUTTON, 70, 40, 70, 30, "clock" );
    fl_set_object_callback( obj, cb_clock, 0 );

    fdui->screen = obj = fl_add_box( FL_UP_BOX, 80, 100, 200, 200, "" );
    fl_set_object_color( obj, FL_WHITE, FL_COL1 );

    fdui->s_hour = obj = fl_add_valslider( FL_HOR_BROWSER_SLIDER, 80, 320, 180, 30, "hour" );
    fl_set_object_callback( obj, cb_hour, 0 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_bounds( obj, 0, 11 );
    fl_set_slider_value( obj, 0 );
    fl_set_slider_step( obj, 1 );
    fl_set_slider_increment( obj, 1, 1 );

    fdui->s_min = obj = fl_add_valslider( FL_HOR_BROWSER_SLIDER, 80, 370, 180, 30, "minutes" );
    fl_set_object_callback( obj, cb_min, 0 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );
    fl_set_slider_bounds( obj, 0, 59 );
    fl_set_slider_value( obj, 0 );
    fl_set_slider_step( obj, 1 );
    fl_set_slider_increment( obj, 1, 1 );

    fl_end_form( );

    fdui->watch_top->fdui = fdui;

    return fdui;
}
