/* Header file generated by fdesign on Thu May 15 14:00:57 2025 */

#ifndef FD_watch_top_h_
#define FD_watch_top_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

void cb_clock( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * watch_top;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * clock;
    FL_OBJECT * screen;
} FD_watch_top;

FD_watch_top * create_form_watch_top( void );

#endif /* FD_watch_top_h_ */
