/* Header file generated by fdesign on Sat May 17 16:02:54 2025 */

#ifndef FD_watch_top_h_
#define FD_watch_top_h_

#include <forms.h>

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void cb_clock( FL_OBJECT *, long );
void cb_hour( FL_OBJECT *, long );
void cb_min( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * watch_top;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * clock;
    FL_OBJECT * screen;
    FL_OBJECT * s_hour;
    FL_OBJECT * s_min;
} FD_watch_top;

FD_watch_top * create_form_watch_top( void );

#if defined __cplusplus
}
#endif

#endif /* FD_watch_top_h_ */
